### PR TITLE
Reduce disk io

### PR DESCRIPTION
**Pull request by jamieabc**
When bitmarkd asks other node's information, original mechanism makes disk io grows with connection.

Since block digest is not changed until new block or fork, this patch adds following changes:
1. use cache to store block digest
2. digest from leveled, not from block and calculated by cpu
3. cache is cleared when fork happens

### CODE REVIEW

**Comment by jamieabc** [comment]
test this please

**Comment by lemonlatte** [comment]
ok

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
test this please

**Comment by hxw** [comment]
test again

**Comment by hxw** [comment]
kindly test this pr, pretty please

**Comment by hxw** [comment]
kindly test this pull request pretty please

**Comment by hxw** [comment]
test this please

**Pull request merged**
