### PR TITLE
Libp2p sync master

### PR DESCRIPTION
**Pull request by pieceofr**
+ Merge Master commit to libp2p :3678a1a :[bitmarkd] update to version 0.12.4-beta.3-1ubuntu1
+ Git rebase for 91 commits seems too difficult to rebase

### CODE REVIEW

**Comment by lemonlatte** [comment]
test it pls

**Comment by pieceofr** [comment]
> test it pls

have done this. 
2020-01-03 15-36-45 的螢幕擷圖

**Comment by pieceofr** [comment]
> test it pls

anything wrong you found?

**Comment by lemonlatte** [comment]
> > test it pls
> 
> Have you found anything wrong?

No. I am asking the jenkins bot to test but it is not triggered.

**Comment by lemonlatte** [comment]
I have merged a PR before. Please fix the conflict and push again.

**Pull request merged**
