### PR TITLE
[Feature] p2p payment watcher

### PR DESCRIPTION
**Pull request by lemonlatte**
## Goal

In the PR, we introduce a new way to validate bitmark transaction payments through p2p protocol from bitcoin and litecoin. This approach mainly improves in two direction:

1. Make bitmarkd not to rely on certain bitcoin/litecoin nodes using RPC nor the centralized discovery nodes using zeromq. 
1. Reduce the storage cost of running a bitcoin/litecoin full node.
Since we only store the headers for a blockchain, the storage size is very small compared to that of a full node. 
Take bitcoin blockchain for example, it would take at about 45 MB to store all its headers. (80bytes of header size x 590,000 blocks ~= 45 MB). However, the storage of a bitcoin full node will take at about 270GB.

## Details

It searches bitcoin/litecoin node over the network by DNS seed and the p2p protocol. Establish enough connection and detect possible transactions with a valid OP_RETURN that contains `payId`. Those transaction will then use to validate pending paid transactions.

The old validation is reserved. We add a `mode` field in configuration for users to determine which method they want for checking the transaction payments.

In order to make this process closed gracefully. I add the `StopAndWait` function for the background and create another PR https://github.com/bitmark-inc/bitmarkd/pull/80 . Since it is not merged yet, some of its codes are appeared in this PR. 

## References

1. [Bitcoin Protocol](https://en.bitcoin.it/wiki/Protocol_documentation)
1. [Btcd](https://github.com/btcsuite/btcd)

### CODE REVIEW

**Comment by hxw** [comment]
to retrigger build

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
run tests

**Comment by lemonlatte** [comment]
run tests

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
test this please

**Comment by lemonlatte** [comment]
test this please

**Comment by hxw** [comment]
test this please

**Pull request merged**
